env:
  es2020: true
  node: true
extends:
  - xo
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "camelcase": "off",
  "no-unused-vars": "off",
  "no-return-await": "off",
  "@typescript-eslint/no-unused-vars": ["error"],
  "indent": ["error", 2, { "SwitchCase": 1 }]
}
