service: aws-node-project

frameworkVersion: '2'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handlers/handler.hello
